### ISSUE TITLE
Url leads to "page not found"

### ISSUE THREAD

**Issue by hariszaf** [merenlab/anvio.org#10]
Hi there. 

I Just found out that on the [Anvi'o User Tutorial for Metagenomic Workflow](https://merenlab.org/2016/06/22/anvio-tutorial-v2/) 
the link that should point out an example of  `anvi-summarize` command, leads to a `page not found` message.

Here is the sentence in case it helps:
*"an example from one of our papers is [here](http://anvio.org/data/INFANT-CLC-SUMMARY-SUPERVISED/)"*

**Comment by meren** [comment]
Thank you very much for your report, @hariszaf. I took care of it, and slightly improved the tutorial overall with this https://github.com/merenlab/web/commit/8cb5bd794d7d67d85d2073600129782e3c9b2ac8. Updates should sync within minutes.

Best wishes,
