### ISSUE TITLE
Page not found from Installation page

### ISSUE THREAD

**Issue by ChrisTrivedi** [merenlab/anvio.org#17]
Hi Anvi'o team,

Just a quick note that on the installation page at the end of [4.3 Troubleshooting](https://anvio.org/install/#when-i-run-anvio-test-for-pangenomics-i-get-errors-related-to-the-functional-enrichment-step), the "... anvi'o resources [here](https://anvio.org/software/anvio) ..." link leads to a page not found. Otherwise, the site is looking really nice! Thanks for all of the hard work and awesome tools...as always!

Cheers,
Chris

**Comment by meren** [comment]
Thank you very much for the heads up, @ChrisTrivedi! It is now fixed.
