### ISSUE TITLE
Link's dead, Jim

### ISSUE THREAD

**Issue by handibles** [merenlab/anvio.org#19]
In. Cred. Ible. Content. Much thanks, will cite.

Dead link tho:

"**_anvi-summarize_**
[...]
The result of anvi-summarize is a static HTML output you can browse in your browser, send to your colleagues, put it on your web page (an example from one of our papers is [here](**http://anvio.org/data/INFANT-CLC-SUMMARY-SUPERVISED/))**, or attach it to your submission as a supplementary data for review. When you run anvi-summarize,"

**Comment by handibles** [comment]
take it back - this was a redirect from the USDA-RSA's mirror of the pipeline, the updated version doesn't have that link anymore. Would be nice to see though!!

**Comment by meren** [comment]
We are working on improving the anvi-server, once it is complete we will certainly update that text with some links :) Thank you, @handibles!
